### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by asigalov61** [YatingMusic/remi#11]
Hey guys!

Just wanted to thank you for this awesome repo/paper/approach. I think you are really onto something here. I will test soon and let you know what I think if you are interested.

The only thing I wanted to humbly recommend is to create a nice Google Colab for your idea so that it can easily be tried and evaluated. This is what I am going to do with your code so that everyone can easily check it out. I hope you do not mind.

Otherwise, great job! Thank you again :)))

AS

**Comment by asigalov61** [comment]
Here guys, sorry for so many posts. I hope you do not mind...

I created a simple colab for your code so that people can try it easily and in a simple way :)

Thank you again.

https://github.com/asigalov61/remi/blob/master/Incredible_REMI_Piano.ipynb

**Comment by remyhuang** [comment]
Thanks!
