### ISSUE TITLE
Training from scratch for Classical Piano

### ISSUE THREAD

**Issue by asigalov61** [YatingMusic/remi#12]
Hey guys,

Another tiny issue here...

Is there any way you can share/help to write a nice training from scratch code for Classical Piano (think MAESTRO or similar Datasets)?

I know you have suggested adjusting parameters of the training data (which is useful) but there is no code. You only provide a fine-tuning code.

So if you can do this/help with this, I will be very grateful to you and your help will be much appreciated.

Thank you again

**Comment by remyhuang** [comment]
I am sorry that we don't have such plans in the near future. 
Maybe this repo can help you! (https://github.com/slSeanWU/jazz_transformer/)

**Comment by asigalov61** [comment]
@remyhuang Yes, thank you so much. Definitely looks interesting and promising. thank you.
