### ISSUE TITLE
The code for evaluation(downbeat and so on)

### ISSUE THREAD

**Issue by theseventhflow** [YatingMusic/remi#19]
Hi,

Thank you for your information about the dataset and I can generate pretty good result! Now I would like to evaluate the beat std, downbeat std and downbeat salience. After doing some research, I think you might use the madmom package to calculate the three scores(I am not sure.), and I am not familiar with that package. Therefore, could you please share your evaluation code with me?

![image](https://user-images.githubusercontent.com/43344805/98111684-f1e63880-1edb-11eb-8fa5-12aa9a261350.png)

**Comment by theseventhflow** [comment]
Hi, I have figured out how to calculate the downbeat. Please ignore my issue. Thanks.

**Comment by remyhuang** [comment]
You can see the RNNDownBeatProcessor and DBNDownBeatTrackingProcessor from madmom. (too busy recently, sorry)

**Comment by theseventhflow** [comment]
No problem! Now I know how to use madmom. Thank you.

**Comment by MarcusLee-awsome** [comment]
Would you mind sharing the code of evaluation?

**Comment by dedededefo** [comment]
> 没问题！现在我知道如何使用 madmom 了。谢谢你。

Hello, do you know where the author used the method of beat and downbeat extraction

**Comment by dedededefo** [comment]
> 你可以看到来自 madmom 的 RNNDownBeatProcessor 和 DBNDownBeatTrackingProcessor。（最近太忙，抱歉）

Hello, excuse me. I want to know where you used the method of beat and downbeat extraction. Thank you
