### ISSUE TITLE
Training on custom MIDI corpus?

### ISSUE THREAD

**Issue by robinsloan** [YatingMusic/remi#2]
Hello! This is a great project, and I was able to get it running immediately. Thank you for sharing it!

Is there a way to train the model from scratch -- and/or fine-tune one of your published models -- on my own corpus of MIDI files?

**Comment by remyhuang** [comment]
Hi! I have uploaded the [`finetune.py`](https://github.com/YatingMusic/remi/blob/master/finetune.py).
Please help me try it and tell me if there is anything wrong!

Thanks,
Remy

**Comment by remyhuang** [comment]
I would like to save every checkpoint per epoch for now. So, you have to choose which checkpoint you like the most to further generate samples. Basically, you can try every checkpoint and listen to the generated output.

In my personal experiments, by using ~30 minutes midi to finetune with one V100, it only took 5-15 minutes to obtain good generated examples.

However, it is stlll based on your data.

Thanks,
Remy

**Comment by robinsloan** [comment]
It works perfectly! Incredible! Thank you so much for the quick reply & the helpful addition. This is great!

**Comment by huangqing6** [comment]
Hello, I was wondering how I can turn my midi file into a file inside REMI-tempo-checkpoint?

**Comment by dedededefo** [comment]
> 它完美地工作！极好的！非常感谢您的快速回复和有用的补充。这很棒！

Hello, can you tell me how to use your MIDI fine-tuning
