### ISSUE TITLE
module 'miditoolkit.pianoroll.parser' has no attribute 'get_pianoroll'

### ISSUE THREAD

**Issue by jjtail** [YatingMusic/remi#4]
HI.
This is a great project.
But , I meet some wrong in  `chord_recognition.py`
module 'miditoolkit.pianoroll.parser' has no attribute 'get_pianoroll' in **line 34**
Isn't the function here supposed to be `miditoolkit.pianoroll.parser.notes2pianoroll`  instead of  

`miditoolkit.pianoroll.parser.get_pianoroll `  ？
Thank u ~

**Comment by remyhuang** [comment]
oops. I think it is because I used an older version of the miditoolkit. As you have mentioned, it should be fixed using `note2pianoroll`. 
Could you try it for me? Then, I can revise it or you can submit a PR!

Thanks,
Remy

**Comment by jjtail** [comment]
HI, Remy
Thank you for your reply.
when I modify it, it works normally.
I used `result / continuation.midi `file and got the same result ([0:10]) as you did in the `midi2remi.ipynb` after using `note2pianoroll` fuction. 
But I'm not sure wether `./data/evaluation/000.midi` is same file to `result / continuation.midi`

**Comment by remyhuang** [comment]
Thanks for your help! I will revise the code and close this issue.
As for the `result/continuation.midi`, it is just an example generated result for listening.

Thanks,
Remy
