### ISSUE TITLE
Data Augmentation Used?

### ISSUE THREAD

**Issue by Akamight** [YatingMusic/remi#6]
After looking at the repository closely, I failed to find any data augmentation (Such as transposition and time stretching) used. So, is there a way that I can add this in or enable this feature somehow?

**Comment by remyhuang** [comment]
I don't use any data augmentation here. Previously, I tried to use pitch transposition and time stretching for my own experiments, but the time required for training became much longer and the results did not show significant improvement.

If you would like to add this feature, it should be an optional file for data augmentation. Welcome to contribute!

-Remy

**Comment by Akamight** [comment]
By the way, is there a way to train this model from scratch? (creating new dictionary, initialize variables, etc.). Currently it doesn't seem like so.

**Comment by remyhuang** [comment]
It's not the main purpose of this repo. I may plan to add this feature in the future when I have time. However, I think it is quite easy to revise my code yourself.
